
SIGHUP	        Hangup (POSIX)
SIGINT	        Terminal interrupt (ANSI)
SIGQUIT	        Terminal quit (POSIX)
SIGILL	        Illegal instruction (ANSI)
SIGTRAP	        Trace trap (POSIX)
SIGIOT	        IOT Trap (4.2 BSD)
SIGBUS	        BUS error (4.2 BSD)
SIGFPE	        Floating point exception (ANSI)
SIGKILL	        Kill(can't be caught or ignored) (POSIX)
SIGUSR1 	User defined signal 1 (POSIX)
SIGSEGV  	Invalid memory segment access (ANSI)
SIGUSR2	        User defined signal 2 (POSIX)
SIGPIPE	        Write on a pipe with no reader, Broken pipe (POSIX)
SIGALRM	        Alarm clock (POSIX)
SIGTERM 	Termination (ANSI)
SIGSTKFLT       Stack fault
SIGCHLD         Child process has stopped or exited, changed (POSIX)
SIGCONT	        Continue executing, if stopped (POSIX)
SIGSTOP	        Stop executing(can't be caught or ignored) (POSIX)
SIGTSTP 	Terminal stop signal (POSIX)
SIGTTIN	        Background process trying to read, from TTY (POSIX)
SIGTTOU	        Background process trying to write, to TTY (POSIX)
